spring:
  profiles:
    active: dev

  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto:
    show-sql:
    open-in-view:
    properties:
      hibernate:
        format_sql:

  jackson:
    serialization:
      write-dates-as-timestamps:
    deserialization:
      fail-on-unknown-properties:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:

server:
  port:

jwt:
  secret:
  expiration: