package Murilo.Wisch.WischGym.domain.enums;

public enum TipoNotificacao {
    CONVITE_RECEBIDO,
    CONVITE_ACEITO,
    CONVITE_RECUSADO,
    MATRICULA_VENCENDO,
    MATRICULA_EXPIRADA,
    MATRICULA_ATIVADA,
    NOVO_ALUNO,
    NOVO_TREINO,
    TREINO_ATUALIZADO,
    TREINO_REMOVIDO,
    PAGAMENTO_ATRASADO,
    PAGAMENTO_REALIZADO
}
